apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shop-ecommerce-monitor
  namespace: monitoring
  labels:
    release: prometheus
    app: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - shop-ecommerce
  selector:
    matchLabels:
      app: shop-ecommerce
  endpoints:
    - port: http
      path: /nginx-status
      interval: 15s
      scrapeTimeout: 10s
